name        : unittest-cpp
version     : 1.6.1
release     : 1
source      :
    - https://github.com/unittest-cpp/unittest-cpp/releases/download/v1.6.1/unittest-cpp-1.6.1.tar.gz : 5b00a217f90fe262d91d09405ef5a8b5d28063da2f701cc58af48d560c4792af
license     : MIT
component   : programming
summary     : A lightweight unit testing framework for C++
description : |
    UnitTest++ is a lightweight unit testing framework for C++. It was designed
    to do test-driven development on a wide variety of platforms. Simplicity,
    portability, speed, and small footprint are all very important aspects of
    UnitTest++. UnitTest++ is mostly standard C++ and makes minimal use of
    advanced library and language features.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install